source 'https://rubygems.org'

gem 'rails',    '~> 5.2'
gem 'pg',       '>= 0.18', '< 2.0'
gem 'puma',     '~> 3.11'
gem 'bootsnap', '>= 1.4.0', require: false

gem 'rails_event_store', github: 'RailsEventStore/rails_event_store'
gem 'dres_client', github: 'RailsEventStore/rails_event_store', glob: 'contrib/distributed_rails_event_store/dres_client/*.gemspec'
gem 'dres_rails', github: 'RailsEventStore/rails_event_store', glob: 'contrib/distributed_rails_event_store/dres_rails/*.gemspec'
