name: multiple_databases_repository
on:
  schedule:
    - cron: "0 17 * * *"
  push:
    paths:
      - "multiple_databases_repository/**"
      - ".github/workflows/multiple_databases_repository.yml"
  pull_request:
    types: [opened, reopened]
    paths:
      - "multiple_databases_repository/**"
      - ".github/workflows/multiple_databases_repository.yml"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY: multiple_databases_repository
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: bin/rspec
        working-directory: ${{ env.WORKING_DIRECTORY }}
